services:
  main:
    image: evilbeaver/onescript:latest
    volumes:
      - "./main.os:/app/main.os"
    working_dir: /app
    stdin_open: true
    tty: true
    command: ["sh", "-c", "stty -icanon -echo 2>/dev/null; oscript main.os"]
